@startuml
title 活动图 — 教师修改成绩或评价
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor Teacher
participant "：首页" as A
participant "：实验列表" as B
participant "：修改学生成绩" as C
participant "：成绩表" as D

Teacher ->A : 进入系统
activate A

A ->B : 选择进入
activate B

B ->C : 选择相应班级
activate C

C ->D :按要求修改成绩，评价

D -->C :修改成功
D -->B :返回最新成绩
@enduml